#spring.application.name=eureka-client
#server.port=8090
#eureka.client.serviceUrl.defaultZone=http://localhost:8080/eureka/

server:
  port: 8090
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8810/eureka/