server:
  port: 8080

spring:
  application:
    name: simple-redis
  redis:
    cluster:
      max-redirects: 3
      nodes:
        - 10.254.57.157:6379
        - 10.254.172.241:6379
    # Redis服务器连接密码（默认为空）
    password: ""
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
