server:
  port: 8080

spring:
  application:
    name: simple-redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.254.57.157
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ""
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0